package com.zxd.lottery.doubleball.crawler.dao.mapper;

import com.zxd.lottery.doubleball.crawler.dao.model.NumberTimes;

public interface NumberTimesDao {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table number_times
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table number_times
     *
     * @mbggenerated
     */
    int insert(NumberTimes record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table number_times
     *
     * @mbggenerated
     */
    int insertSelective(NumberTimes record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table number_times
     *
     * @mbggenerated
     */
    NumberTimes selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table number_times
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(NumberTimes record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table number_times
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(NumberTimes record);
}