package com.zxd.lottery.doubleball.crawler.dao.model;

public class NumberTimes {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column number_times.id
     *
     * @mbggenerated
     */
    private String id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column number_times.num01
     *
     * @mbggenerated
     */
    private Integer num01;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column number_times.num02
     *
     * @mbggenerated
     */
    private Integer num02;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column number_times.num03
     *
     * @mbggenerated
     */
    private Integer num03;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column number_times.num04
     *
     * @mbggenerated
     */
    private Integer num04;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column number_times.num05
     *
     * @mbggenerated
     */
    private Integer num05;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column number_times.num06
     *
     * @mbggenerated
     */
    private Integer num06;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column number_times.num07
     *
     * @mbggenerated
     */
    private Integer num07;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column number_times.num08
     *
     * @mbggenerated
     */
    private Integer num08;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column number_times.num09
     *
     * @mbggenerated
     */
    private Integer num09;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column number_times.num10
     *
     * @mbggenerated
     */
    private Integer num10;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column number_times.num11
     *
     * @mbggenerated
     */
    private Integer num11;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column number_times.num12
     *
     * @mbggenerated
     */
    private Integer num12;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column number_times.num13
     *
     * @mbggenerated
     */
    private Integer num13;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column number_times.num14
     *
     * @mbggenerated
     */
    private Integer num14;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column number_times.num15
     *
     * @mbggenerated
     */
    private Integer num15;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column number_times.num16
     *
     * @mbggenerated
     */
    private Integer num16;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column number_times.num17
     *
     * @mbggenerated
     */
    private Integer num17;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column number_times.num18
     *
     * @mbggenerated
     */
    private Integer num18;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column number_times.num19
     *
     * @mbggenerated
     */
    private Integer num19;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column number_times.num20
     *
     * @mbggenerated
     */
    private Integer num20;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column number_times.num21
     *
     * @mbggenerated
     */
    private Integer num21;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column number_times.num22
     *
     * @mbggenerated
     */
    private Integer num22;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column number_times.num23
     *
     * @mbggenerated
     */
    private Integer num23;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column number_times.num24
     *
     * @mbggenerated
     */
    private Integer num24;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column number_times.num25
     *
     * @mbggenerated
     */
    private Integer num25;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column number_times.num26
     *
     * @mbggenerated
     */
    private Integer num26;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column number_times.num27
     *
     * @mbggenerated
     */
    private Integer num27;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column number_times.num28
     *
     * @mbggenerated
     */
    private Integer num28;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column number_times.num29
     *
     * @mbggenerated
     */
    private Integer num29;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column number_times.num30
     *
     * @mbggenerated
     */
    private Integer num30;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column number_times.num31
     *
     * @mbggenerated
     */
    private Integer num31;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column number_times.num32
     *
     * @mbggenerated
     */
    private Integer num32;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column number_times.num33
     *
     * @mbggenerated
     */
    private Integer num33;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column number_times.id
     *
     * @return the value of number_times.id
     *
     * @mbggenerated
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column number_times.id
     *
     * @param id the value for number_times.id
     *
     * @mbggenerated
     */
    public void setId(String id) {
        this.id = id == null ? null : id.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column number_times.num01
     *
     * @return the value of number_times.num01
     *
     * @mbggenerated
     */
    public Integer getNum01() {
        return num01;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column number_times.num01
     *
     * @param num01 the value for number_times.num01
     *
     * @mbggenerated
     */
    public void setNum01(Integer num01) {
        this.num01 = num01;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column number_times.num02
     *
     * @return the value of number_times.num02
     *
     * @mbggenerated
     */
    public Integer getNum02() {
        return num02;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column number_times.num02
     *
     * @param num02 the value for number_times.num02
     *
     * @mbggenerated
     */
    public void setNum02(Integer num02) {
        this.num02 = num02;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column number_times.num03
     *
     * @return the value of number_times.num03
     *
     * @mbggenerated
     */
    public Integer getNum03() {
        return num03;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column number_times.num03
     *
     * @param num03 the value for number_times.num03
     *
     * @mbggenerated
     */
    public void setNum03(Integer num03) {
        this.num03 = num03;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column number_times.num04
     *
     * @return the value of number_times.num04
     *
     * @mbggenerated
     */
    public Integer getNum04() {
        return num04;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column number_times.num04
     *
     * @param num04 the value for number_times.num04
     *
     * @mbggenerated
     */
    public void setNum04(Integer num04) {
        this.num04 = num04;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column number_times.num05
     *
     * @return the value of number_times.num05
     *
     * @mbggenerated
     */
    public Integer getNum05() {
        return num05;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column number_times.num05
     *
     * @param num05 the value for number_times.num05
     *
     * @mbggenerated
     */
    public void setNum05(Integer num05) {
        this.num05 = num05;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column number_times.num06
     *
     * @return the value of number_times.num06
     *
     * @mbggenerated
     */
    public Integer getNum06() {
        return num06;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column number_times.num06
     *
     * @param num06 the value for number_times.num06
     *
     * @mbggenerated
     */
    public void setNum06(Integer num06) {
        this.num06 = num06;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column number_times.num07
     *
     * @return the value of number_times.num07
     *
     * @mbggenerated
     */
    public Integer getNum07() {
        return num07;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column number_times.num07
     *
     * @param num07 the value for number_times.num07
     *
     * @mbggenerated
     */
    public void setNum07(Integer num07) {
        this.num07 = num07;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column number_times.num08
     *
     * @return the value of number_times.num08
     *
     * @mbggenerated
     */
    public Integer getNum08() {
        return num08;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column number_times.num08
     *
     * @param num08 the value for number_times.num08
     *
     * @mbggenerated
     */
    public void setNum08(Integer num08) {
        this.num08 = num08;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column number_times.num09
     *
     * @return the value of number_times.num09
     *
     * @mbggenerated
     */
    public Integer getNum09() {
        return num09;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column number_times.num09
     *
     * @param num09 the value for number_times.num09
     *
     * @mbggenerated
     */
    public void setNum09(Integer num09) {
        this.num09 = num09;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column number_times.num10
     *
     * @return the value of number_times.num10
     *
     * @mbggenerated
     */
    public Integer getNum10() {
        return num10;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column number_times.num10
     *
     * @param num10 the value for number_times.num10
     *
     * @mbggenerated
     */
    public void setNum10(Integer num10) {
        this.num10 = num10;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column number_times.num11
     *
     * @return the value of number_times.num11
     *
     * @mbggenerated
     */
    public Integer getNum11() {
        return num11;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column number_times.num11
     *
     * @param num11 the value for number_times.num11
     *
     * @mbggenerated
     */
    public void setNum11(Integer num11) {
        this.num11 = num11;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column number_times.num12
     *
     * @return the value of number_times.num12
     *
     * @mbggenerated
     */
    public Integer getNum12() {
        return num12;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column number_times.num12
     *
     * @param num12 the value for number_times.num12
     *
     * @mbggenerated
     */
    public void setNum12(Integer num12) {
        this.num12 = num12;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column number_times.num13
     *
     * @return the value of number_times.num13
     *
     * @mbggenerated
     */
    public Integer getNum13() {
        return num13;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column number_times.num13
     *
     * @param num13 the value for number_times.num13
     *
     * @mbggenerated
     */
    public void setNum13(Integer num13) {
        this.num13 = num13;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column number_times.num14
     *
     * @return the value of number_times.num14
     *
     * @mbggenerated
     */
    public Integer getNum14() {
        return num14;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column number_times.num14
     *
     * @param num14 the value for number_times.num14
     *
     * @mbggenerated
     */
    public void setNum14(Integer num14) {
        this.num14 = num14;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column number_times.num15
     *
     * @return the value of number_times.num15
     *
     * @mbggenerated
     */
    public Integer getNum15() {
        return num15;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column number_times.num15
     *
     * @param num15 the value for number_times.num15
     *
     * @mbggenerated
     */
    public void setNum15(Integer num15) {
        this.num15 = num15;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column number_times.num16
     *
     * @return the value of number_times.num16
     *
     * @mbggenerated
     */
    public Integer getNum16() {
        return num16;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column number_times.num16
     *
     * @param num16 the value for number_times.num16
     *
     * @mbggenerated
     */
    public void setNum16(Integer num16) {
        this.num16 = num16;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column number_times.num17
     *
     * @return the value of number_times.num17
     *
     * @mbggenerated
     */
    public Integer getNum17() {
        return num17;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column number_times.num17
     *
     * @param num17 the value for number_times.num17
     *
     * @mbggenerated
     */
    public void setNum17(Integer num17) {
        this.num17 = num17;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column number_times.num18
     *
     * @return the value of number_times.num18
     *
     * @mbggenerated
     */
    public Integer getNum18() {
        return num18;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column number_times.num18
     *
     * @param num18 the value for number_times.num18
     *
     * @mbggenerated
     */
    public void setNum18(Integer num18) {
        this.num18 = num18;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column number_times.num19
     *
     * @return the value of number_times.num19
     *
     * @mbggenerated
     */
    public Integer getNum19() {
        return num19;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column number_times.num19
     *
     * @param num19 the value for number_times.num19
     *
     * @mbggenerated
     */
    public void setNum19(Integer num19) {
        this.num19 = num19;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column number_times.num20
     *
     * @return the value of number_times.num20
     *
     * @mbggenerated
     */
    public Integer getNum20() {
        return num20;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column number_times.num20
     *
     * @param num20 the value for number_times.num20
     *
     * @mbggenerated
     */
    public void setNum20(Integer num20) {
        this.num20 = num20;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column number_times.num21
     *
     * @return the value of number_times.num21
     *
     * @mbggenerated
     */
    public Integer getNum21() {
        return num21;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column number_times.num21
     *
     * @param num21 the value for number_times.num21
     *
     * @mbggenerated
     */
    public void setNum21(Integer num21) {
        this.num21 = num21;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column number_times.num22
     *
     * @return the value of number_times.num22
     *
     * @mbggenerated
     */
    public Integer getNum22() {
        return num22;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column number_times.num22
     *
     * @param num22 the value for number_times.num22
     *
     * @mbggenerated
     */
    public void setNum22(Integer num22) {
        this.num22 = num22;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column number_times.num23
     *
     * @return the value of number_times.num23
     *
     * @mbggenerated
     */
    public Integer getNum23() {
        return num23;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column number_times.num23
     *
     * @param num23 the value for number_times.num23
     *
     * @mbggenerated
     */
    public void setNum23(Integer num23) {
        this.num23 = num23;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column number_times.num24
     *
     * @return the value of number_times.num24
     *
     * @mbggenerated
     */
    public Integer getNum24() {
        return num24;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column number_times.num24
     *
     * @param num24 the value for number_times.num24
     *
     * @mbggenerated
     */
    public void setNum24(Integer num24) {
        this.num24 = num24;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column number_times.num25
     *
     * @return the value of number_times.num25
     *
     * @mbggenerated
     */
    public Integer getNum25() {
        return num25;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column number_times.num25
     *
     * @param num25 the value for number_times.num25
     *
     * @mbggenerated
     */
    public void setNum25(Integer num25) {
        this.num25 = num25;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column number_times.num26
     *
     * @return the value of number_times.num26
     *
     * @mbggenerated
     */
    public Integer getNum26() {
        return num26;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column number_times.num26
     *
     * @param num26 the value for number_times.num26
     *
     * @mbggenerated
     */
    public void setNum26(Integer num26) {
        this.num26 = num26;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column number_times.num27
     *
     * @return the value of number_times.num27
     *
     * @mbggenerated
     */
    public Integer getNum27() {
        return num27;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column number_times.num27
     *
     * @param num27 the value for number_times.num27
     *
     * @mbggenerated
     */
    public void setNum27(Integer num27) {
        this.num27 = num27;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column number_times.num28
     *
     * @return the value of number_times.num28
     *
     * @mbggenerated
     */
    public Integer getNum28() {
        return num28;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column number_times.num28
     *
     * @param num28 the value for number_times.num28
     *
     * @mbggenerated
     */
    public void setNum28(Integer num28) {
        this.num28 = num28;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column number_times.num29
     *
     * @return the value of number_times.num29
     *
     * @mbggenerated
     */
    public Integer getNum29() {
        return num29;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column number_times.num29
     *
     * @param num29 the value for number_times.num29
     *
     * @mbggenerated
     */
    public void setNum29(Integer num29) {
        this.num29 = num29;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column number_times.num30
     *
     * @return the value of number_times.num30
     *
     * @mbggenerated
     */
    public Integer getNum30() {
        return num30;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column number_times.num30
     *
     * @param num30 the value for number_times.num30
     *
     * @mbggenerated
     */
    public void setNum30(Integer num30) {
        this.num30 = num30;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column number_times.num31
     *
     * @return the value of number_times.num31
     *
     * @mbggenerated
     */
    public Integer getNum31() {
        return num31;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column number_times.num31
     *
     * @param num31 the value for number_times.num31
     *
     * @mbggenerated
     */
    public void setNum31(Integer num31) {
        this.num31 = num31;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column number_times.num32
     *
     * @return the value of number_times.num32
     *
     * @mbggenerated
     */
    public Integer getNum32() {
        return num32;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column number_times.num32
     *
     * @param num32 the value for number_times.num32
     *
     * @mbggenerated
     */
    public void setNum32(Integer num32) {
        this.num32 = num32;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column number_times.num33
     *
     * @return the value of number_times.num33
     *
     * @mbggenerated
     */
    public Integer getNum33() {
        return num33;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column number_times.num33
     *
     * @param num33 the value for number_times.num33
     *
     * @mbggenerated
     */
    public void setNum33(Integer num33) {
        this.num33 = num33;
    }
}